# Question 1

In [16]:
def dydt(y,t):
    return((-2*y*t))

def rungeKutta(t0,y0,y,h):
    n = int((t-t0)/h)
    y=y0
    for i in range (1, n+1):
        k1 = dydt(t0,y)
        k2 = dydt(t0+0.5*h, y+0.5*h*k1)
        k3 = dydt(t0+0.5*h, y+0.5*h*k2)
        k4 = dydt(t0+h, y+h*k3)
        
        y = y + (1/6)*h*(k1+2*k2+2*k3+k4)
        t0 = t0 + h
    return y

t0=0
y=1
t=2
h=0.2
print ('The value of y at t is:', rungeKutta(t0,y,t,h))

The value of y at t is: 0.018457694145413515


In [ ]:
import math
from matplotlib import pyplot as plt

x = list(range(0,3))
y = [math.pow(num,2) for num in x]

plt.plot(x,y,colour='red')
plt.title('y(t) versus (t)')
plt.xlabel('t value from 0 to 2')
plt.ylable('Y value')
plt.show()

# Question 2

In [4]:
import numpy as np
import scipy as sc

A = np.array([[2,4,6],[5,3,2],[7,8,9]])

print(A)

[[2 4 6]
 [5 3 2]
 [7 8 9]]


In [5]:
B = np.array([[18],[13],[30]])

print(B)

[[18]
 [13]
 [30]]


In [6]:
solution = sc.linalg.solve(A,B)

print(solution)

[[ 4.5]
 [-7.5]
 [ 6.5]]


# Question 3

In [ ]:
import requests

api_url = "https://api.open-meteo.com/v1/forecast?latitude=2.5&longitude=112.5&hourly=temperature_2m&timezone=Asia%2FSingapore&forecast_days=1"
response = requests.get(api_url)
temperature_2m = response.json()

while True:
    day_name = input("Enter the day: ")

    day_found = False
    for day in temperature_2m:
        print(f"Temperature of {day_name}: {day['temperature_2m']}")
        day_found = True
        break

    if not day_found:
        print(f"{day_name} is not found in the data")

In [41]:
json_data = {
    "hourly_time_points" :[
        
        "2024-01-11T00:00",
        "2024-01-11T01:00",
        "2024-01-11T02:00",
        "2024-01-11T03:00",
        "2024-01-11T04:00",
        "2024-01-11T05:00",
        "2024-01-11T06:00",
        "2024-01-11T07:00",
        "2024-01-11T08:00",
        "2024-01-11T09:00",
        "2024-01-11T10:00",
        "2024-01-11T11:00",
        "2024-01-11T12:00",
        "2024-01-11T13:00",
        "2024-01-11T14:00",
        "2024-01-11T15:00",
        "2024-01-11T16:00",
        "2024-01-11T17:00",
        "2024-01-11T18:00",
        "2024-01-11T19:00",
        "2024-01-11T20:00",
        "2024-01-11T21:00",
        "2024-01-11T22:00",
        "2024-01-11T23:00"
    ],

    "temperature" = [
        23.8,
        23.5,
        23.3,
        23.2,
        23.1,
        23.1,
        23,
        23,
        24.2,
        25.6,
        26.8,
        27.9,
        28.4,
        28.9,
        28.6,
        28,
        27.8,
        26.9,
        26,
        25.3,
        25,
        24.7,
        24.6,
        24.4
    ]
}

time = json_data["hourly_time_points"]
temperature = json_data["temperature"]

plt.plot(time,temperature,color="red")
plt.title("Temperature")
plt.xlabel("time")
plt.ylabel("temperature")
plt.show()

SyntaxError: ':' expected after dictionary key (3399566096.py, line 30)